In [1]:
# First Import the necessary Libraries & To Load the Dataset 

import csv

import numpy as np
import pandas as pd

df = pd.read_csv("Lagos_LGA_Education_Dataset.csv")

df.head(8)

,Row_ID,State,Ownership,Level,LGA,Granularity,Data_Year,Year_Start,Learners,Male_Learners,...,Learner_Toilet_Ratio,Female_Teachers_PCT,Special_Needs_Learners,Est_Teachers,Est_Classrooms,Est_Toilets,LTR_Gap_vs_UBE35,Teachers_Needed_To_Meet_UBE35,Enrolment_Change_PCT_vs_Prev_Year,Source
0,1,Lagos,Public,Primary,Agege,LGA,2016/2017,2016,18863,9477.0,...,NaN,NaN,NaN,673.7,NaN,NaN,-7.0,0.0,NaN,"Lagos Bureau of Statistics, Spotlight on Lagos..."
1,2,Lagos,Public,Primary,Ajeromi/Ifelodun,LGA,2016/2017,2016,23660,11776.0,...,NaN,NaN,NaN,422.5,NaN,NaN,21.0,254.0,NaN,"Lagos Bureau of Statistics, Spotlight on Lagos..."
2,3,Lagos,Public,Primary,Alimosho,LGA,2016/2017,2016,44678,22666.0,...,NaN,NaN,NaN,1396.2,NaN,NaN,-3.0,0.0,NaN,"Lagos Bureau of Statistics, Spotlight on Lagos..."
3,4,Lagos,Public,Primary,Amuwo Odofin,LGA,2016/2017,2016,12335,5825.0,...,NaN,NaN,NaN,280.3,NaN,NaN,9.0,72.0,NaN,"Lagos Bureau of Statistics, Spotlight on Lagos..."
4,5,Lagos,Public,Primary,Apapa,LGA,2016/2017,2016,8529,4257.0,...,NaN,NaN,NaN,250.9,NaN,NaN,-1.0,0.0,NaN,"Lagos Bureau of Statistics, Spotlight on Lagos..."
5,6,Lagos,Public,Primary,Badagry,LGA,2016/2017,2016,27736,14195.0,...,NaN,NaN,NaN,543.8,NaN,NaN,16.0,249.0,NaN,"Lagos Bureau of Statistics, Spotlight on Lagos..."
6,7,Lagos,Public,Primary,Epe,LGA,2016/2017,2016,20850,10662.0,...,NaN,NaN,NaN,417.0,NaN,NaN,15.0,179.0,NaN,"Lagos Bureau of Statistics, Spotlight on Lagos..."
7,8,Lagos,Public,Primary,Eti-Osa,LGA,2016/2017,2016,13231,6294.0,...,NaN,NaN,NaN,264.6,NaN,NaN,15.0,113.0,NaN,"Lagos Bureau of Statistics, Spotlight on Lagos..."

In [2]:
df.tail(6)

,Row_ID,State,Ownership,Level,LGA,Granularity,Data_Year,Year_Start,Learners,Male_Learners,...,Learner_Toilet_Ratio,Female_Teachers_PCT,Special_Needs_Learners,Est_Teachers,Est_Classrooms,Est_Toilets,LTR_Gap_vs_UBE35,Teachers_Needed_To_Meet_UBE35,Enrolment_Change_PCT_vs_Prev_Year,Source
354,355,Lagos,Public,Tech/Voc,Lagos Mainland,LGA,2024/2025,2024,0,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,DNEMIS Annual School Census 2024 (emis.educati...
355,356,Lagos,Public,Tech/Voc,Mushin,LGA,2024/2025,2024,0,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,DNEMIS Annual School Census 2024 (emis.educati...
356,357,Lagos,Public,Tech/Voc,Ojo,LGA,2024/2025,2024,0,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,DNEMIS Annual School Census 2024 (emis.educati...
357,358,Lagos,Public,Tech/Voc,Oshodi/Isolo,LGA,2024/2025,2024,0,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,DNEMIS Annual School Census 2024 (emis.educati...
358,359,Lagos,Public,Tech/Voc,Shomolu,LGA,2024/2025,2024,0,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,DNEMIS Annual School Census 2024 (emis.educati...
359,360,Lagos,Public,Tech/Voc,Surulere,LGA,2024/2025,2024,0,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,DNEMIS Annual School Census 2024 (emis.educati...

In [3]:
# To Check the Shape of the Dataset

df.shape

(360, 24)

In [4]:
# To Check the Information of the Dataset

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Row_ID                             360 non-null    int64
 1   State                              360 non-null    str
 2   Ownership                          360 non-null    str
 3   Level                              360 non-null    str
 4   LGA                                360 non-null    str
 5   Granularity                        360 non-null    str
 6   Data_Year                          360 non-null    str
 7   Year_Start                         360 non-null    int64
 8   Learners                           360 non-null    int64
 9   Male_Learners                      240 non-null    float64
 10  Female_Learners                    240 non-null    float64
 11  Female_Learners_PCT                340 non-null    float64
 12  Learner_Teacher_Ratio              323 non-null    float64
 13  Learner_Classroom_Ratio            62 non-null     float64
 14  Learner_Toilet_Ratio               100 non-null    float64
 15  Female_Teachers_PCT                83 non-null     float64
 16  Special_Needs_Learners             120 non-null    float64
 17  Est_Teachers                       323 non-null    float64
 18  Est_Classrooms                     62 non-null     float64
 19  Est_Toilets                        100 non-null    float64
 20  LTR_Gap_vs_UBE35                   323 non-null    float64
 21  Teachers_Needed_To_Meet_UBE35      323 non-null    float64
 22  Enrolment_Change_PCT_vs_Prev_Year  180 non-null    float64
 23  Source                             360 non-null    str
dtypes: float64(14), int64(3), str(7)
memory usage: 67.6 KB

In [5]:
# To Check Statistical Summary of the Dataset

df.describe()

,Row_ID,Year_Start,Learners,Male_Learners,Female_Learners,Female_Learners_PCT,Learner_Teacher_Ratio,Learner_Classroom_Ratio,Learner_Toilet_Ratio,Female_Teachers_PCT,Special_Needs_Learners,Est_Teachers,Est_Classrooms,Est_Toilets,LTR_Gap_vs_UBE35,Teachers_Needed_To_Meet_UBE35,Enrolment_Change_PCT_vs_Prev_Year
count,360.000000,360.000000,360.000000,240.000000,240.000000,340.000000,323.000000,62.000000,100.000000,83.000000,120.000000,323.000000,62.000000,100.000000,323.000000,323.000000,180.000000
mean,180.500000,2019.666667,16749.588889,8158.858333,8482.016667,51.396471,36.214551,53.933871,34.527000,68.357831,42.466667,745.086687,339.135484,848.354000,1.214551,63.866873,1.962778
std,104.067286,3.201671,18746.251337,5158.472373,5101.810144,5.997171,16.294312,25.671768,22.171771,10.180027,115.927675,1569.820422,265.042293,1624.843349,16.294312,118.857727,7.052651
min,1.000000,2016.000000,0.000000,1849.000000,1911.000000,16.200000,7.600000,7.900000,0.500000,41.600000,0.000000,86.700000,23.000000,5.000000,-27.400000,0.000000,-14.600000
25%,90.750000,2017.000000,8516.250000,4644.000000,5010.500000,49.700000,26.000000,33.300000,15.950000,63.950000,0.000000,292.800000,158.300000,153.050000,-9.000000,0.000000,-2.950000
50%,180.500000,2018.500000,13158.000000,6921.500000,7217.500000,50.900000,33.000000,54.750000,33.650000,69.100000,7.000000,419.800000,226.650000,293.000000,-2.000000,0.000000,1.650000
75%,270.250000,2024.000000,19754.250000,9409.000000,10267.000000,52.600000,44.000000,72.975000,47.725000,74.300000,32.000000,590.800000,445.275000,564.725000,9.000000,85.000000,5.525000
max,360.000000,2024.000000,228650.000000,29010.000000,29392.000000,82.600000,117.700000,100.100000,86.100000,88.400000,1016.000000,17322.000000,1411.900000,10393.200000,82.700000,848.000000,31.600000

In [6]:
# To Check Missing Values in the Dataset

df.isnull().sum()

Row_ID                                 0
State                                  0
Ownership                              0
Level                                  0
LGA                                    0
Granularity                            0
Data_Year                              0
Year_Start                             0
Learners                               0
Male_Learners                        120
Female_Learners                      120
Female_Learners_PCT                   20
Learner_Teacher_Ratio                 37
Learner_Classroom_Ratio              298
Learner_Toilet_Ratio                 260
Female_Teachers_PCT                  277
Special_Needs_Learners               240
Est_Teachers                          37
Est_Classrooms                       298
Est_Toilets                          260
LTR_Gap_vs_UBE35                      37
Teachers_Needed_To_Meet_UBE35         37
Enrolment_Change_PCT_vs_Prev_Year    180
Source                                 0
dtype: int64

##### CLEANING THE DATA

In [7]:
# WORKING ON A COPY

df_clean = df.copy()

print("Working Copy Created:", df_clean.shape)



print("Original Dataset:    ", df.shape)

Working Copy Created: (360, 24)
Original Dataset:     (360, 24)

In [8]:
df_clean.describe()

,Row_ID,Year_Start,Learners,Male_Learners,Female_Learners,Female_Learners_PCT,Learner_Teacher_Ratio,Learner_Classroom_Ratio,Learner_Toilet_Ratio,Female_Teachers_PCT,Special_Needs_Learners,Est_Teachers,Est_Classrooms,Est_Toilets,LTR_Gap_vs_UBE35,Teachers_Needed_To_Meet_UBE35,Enrolment_Change_PCT_vs_Prev_Year
count,360.000000,360.000000,360.000000,240.000000,240.000000,340.000000,323.000000,62.000000,100.000000,83.000000,120.000000,323.000000,62.000000,100.000000,323.000000,323.000000,180.000000
mean,180.500000,2019.666667,16749.588889,8158.858333,8482.016667,51.396471,36.214551,53.933871,34.527000,68.357831,42.466667,745.086687,339.135484,848.354000,1.214551,63.866873,1.962778
std,104.067286,3.201671,18746.251337,5158.472373,5101.810144,5.997171,16.294312,25.671768,22.171771,10.180027,115.927675,1569.820422,265.042293,1624.843349,16.294312,118.857727,7.052651
min,1.000000,2016.000000,0.000000,1849.000000,1911.000000,16.200000,7.600000,7.900000,0.500000,41.600000,0.000000,86.700000,23.000000,5.000000,-27.400000,0.000000,-14.600000
25%,90.750000,2017.000000,8516.250000,4644.000000,5010.500000,49.700000,26.000000,33.300000,15.950000,63.950000,0.000000,292.800000,158.300000,153.050000,-9.000000,0.000000,-2.950000
50%,180.500000,2018.500000,13158.000000,6921.500000,7217.500000,50.900000,33.000000,54.750000,33.650000,69.100000,7.000000,419.800000,226.650000,293.000000,-2.000000,0.000000,1.650000
75%,270.250000,2024.000000,19754.250000,9409.000000,10267.000000,52.600000,44.000000,72.975000,47.725000,74.300000,32.000000,590.800000,445.275000,564.725000,9.000000,85.000000,5.525000
max,360.000000,2024.000000,228650.000000,29010.000000,29392.000000,82.600000,117.700000,100.100000,86.100000,88.400000,1016.000000,17322.000000,1411.900000,10393.200000,82.700000,848.000000,31.600000

In [9]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Row_ID                             360 non-null    int64
 1   State                              360 non-null    str
 2   Ownership                          360 non-null    str
 3   Level                              360 non-null    str
 4   LGA                                360 non-null    str
 5   Granularity                        360 non-null    str
 6   Data_Year                          360 non-null    str
 7   Year_Start                         360 non-null    int64
 8   Learners                           360 non-null    int64
 9   Male_Learners                      240 non-null    float64
 10  Female_Learners                    240 non-null    float64
 11  Female_Learners_PCT                340 non-null    float64
 12  Learner_Teacher_Ratio              323 non-null    float64
 13  Learner_Classroom_Ratio            62 non-null     float64
 14  Learner_Toilet_Ratio               100 non-null    float64
 15  Female_Teachers_PCT                83 non-null     float64
 16  Special_Needs_Learners             120 non-null    float64
 17  Est_Teachers                       323 non-null    float64
 18  Est_Classrooms                     62 non-null     float64
 19  Est_Toilets                        100 non-null    float64
 20  LTR_Gap_vs_UBE35                   323 non-null    float64
 21  Teachers_Needed_To_Meet_UBE35      323 non-null    float64
 22  Enrolment_Change_PCT_vs_Prev_Year  180 non-null    float64
 23  Source                             360 non-null    str
dtypes: float64(14), int64(3), str(7)
memory usage: 67.6 KB

In [10]:
# To Change the Data Types of some Dataset

df_clean["Row_ID"] = df_clean["Row_ID"].astype("Int64").astype(str)

df_clean["Teachers_Needed_To_Meet_UBE35"] = df_clean["Teachers_Needed_To_Meet_UBE35"].astype("float64").round().astype("Int64")

df_clean["Special_Needs_Learners"] = df_clean["Special_Needs_Learners"].astype("float64").astype("Int64")

df_clean.head(3)

,Row_ID,State,Ownership,Level,LGA,Granularity,Data_Year,Year_Start,Learners,Male_Learners,...,Learner_Toilet_Ratio,Female_Teachers_PCT,Special_Needs_Learners,Est_Teachers,Est_Classrooms,Est_Toilets,LTR_Gap_vs_UBE35,Teachers_Needed_To_Meet_UBE35,Enrolment_Change_PCT_vs_Prev_Year,Source
0,1,Lagos,Public,Primary,Agege,LGA,2016/2017,2016,18863,9477.0,...,NaN,NaN,<NA>,673.7,NaN,NaN,-7.0,0,NaN,"Lagos Bureau of Statistics, Spotlight on Lagos..."
1,2,Lagos,Public,Primary,Ajeromi/Ifelodun,LGA,2016/2017,2016,23660,11776.0,...,NaN,NaN,<NA>,422.5,NaN,NaN,21.0,254,NaN,"Lagos Bureau of Statistics, Spotlight on Lagos..."
2,3,Lagos,Public,Primary,Alimosho,LGA,2016/2017,2016,44678,22666.0,...,NaN,NaN,<NA>,1396.2,NaN,NaN,-3.0,0,NaN,"Lagos Bureau of Statistics, Spotlight on Lagos..."

#### **FIXING DATA TYPES**

##### **Row_ID** changed from Integal(Int64) to string(str) because it is an identifier, not a quantity or a calculative column.
##### **Teachers_Needed_To_Meet_UBE35 & Special_Needs_Learners** changed from Decimals, fractions, or scientific notation(float64) to whole numbers(Int64), since teachers and students are counted in whole numbers. The capital-I Int64 type is used because it supports missing values.
##### **Learner_Teacher_Ratio & LTR_Gap_vs_UBE35** kept as decimals(float64), because ratios naturally contain decimals.
##### **Year_Start** kept as an integer, so it can be used for sorting and for splitting the data by year.

In [11]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Row_ID                             360 non-null    str
 1   State                              360 non-null    str
 2   Ownership                          360 non-null    str
 3   Level                              360 non-null    str
 4   LGA                                360 non-null    str
 5   Granularity                        360 non-null    str
 6   Data_Year                          360 non-null    str
 7   Year_Start                         360 non-null    int64
 8   Learners                           360 non-null    int64
 9   Male_Learners                      240 non-null    float64
 10  Female_Learners                    240 non-null    float64
 11  Female_Learners_PCT                340 non-null    float64
 12  Learner_Teacher_Ratio              323 non-null    float64
 13  Learner_Classroom_Ratio            62 non-null     float64
 14  Learner_Toilet_Ratio               100 non-null    float64
 15  Female_Teachers_PCT                83 non-null     float64
 16  Special_Needs_Learners             120 non-null    Int64
 17  Est_Teachers                       323 non-null    float64
 18  Est_Classrooms                     62 non-null     float64
 19  Est_Toilets                        100 non-null    float64
 20  LTR_Gap_vs_UBE35                   323 non-null    float64
 21  Teachers_Needed_To_Meet_UBE35      323 non-null    Int64
 22  Enrolment_Change_PCT_vs_Prev_Year  180 non-null    float64
 23  Source                             360 non-null    str
dtypes: Int64(2), float64(12), int64(2), str(8)
memory usage: 68.3 KB

In [12]:
df_clean.describe()

,Year_Start,Learners,Male_Learners,Female_Learners,Female_Learners_PCT,Learner_Teacher_Ratio,Learner_Classroom_Ratio,Learner_Toilet_Ratio,Female_Teachers_PCT,Special_Needs_Learners,Est_Teachers,Est_Classrooms,Est_Toilets,LTR_Gap_vs_UBE35,Teachers_Needed_To_Meet_UBE35,Enrolment_Change_PCT_vs_Prev_Year
count,360.000000,360.000000,240.000000,240.000000,340.000000,323.000000,62.000000,100.000000,83.000000,120.0,323.000000,62.000000,100.000000,323.000000,323.0,180.000000
mean,2019.666667,16749.588889,8158.858333,8482.016667,51.396471,36.214551,53.933871,34.527000,68.357831,42.466667,745.086687,339.135484,848.354000,1.214551,63.866873,1.962778
std,3.201671,18746.251337,5158.472373,5101.810144,5.997171,16.294312,25.671768,22.171771,10.180027,115.927675,1569.820422,265.042293,1624.843349,16.294312,118.857727,7.052651
min,2016.000000,0.000000,1849.000000,1911.000000,16.200000,7.600000,7.900000,0.500000,41.600000,0.0,86.700000,23.000000,5.000000,-27.400000,0.0,-14.600000
25%,2017.000000,8516.250000,4644.000000,5010.500000,49.700000,26.000000,33.300000,15.950000,63.950000,0.0,292.800000,158.300000,153.050000,-9.000000,0.0,-2.950000
50%,2018.500000,13158.000000,6921.500000,7217.500000,50.900000,33.000000,54.750000,33.650000,69.100000,7.0,419.800000,226.650000,293.000000,-2.000000,0.0,1.650000
75%,2024.000000,19754.250000,9409.000000,10267.000000,52.600000,44.000000,72.975000,47.725000,74.300000,32.0,590.800000,445.275000,564.725000,9.000000,85.0,5.525000
max,2024.000000,228650.000000,29010.000000,29392.000000,82.600000,117.700000,100.100000,86.100000,88.400000,1016.0,17322.000000,1411.900000,10393.200000,82.700000,848.0,31.600000

In [13]:
df_clean.isnull().sum()

Row_ID                                 0
State                                  0
Ownership                              0
Level                                  0
LGA                                    0
Granularity                            0
Data_Year                              0
Year_Start                             0
Learners                               0
Male_Learners                        120
Female_Learners                      120
Female_Learners_PCT                   20
Learner_Teacher_Ratio                 37
Learner_Classroom_Ratio              298
Learner_Toilet_Ratio                 260
Female_Teachers_PCT                  277
Special_Needs_Learners               240
Est_Teachers                          37
Est_Classrooms                       298
Est_Toilets                          260
LTR_Gap_vs_UBE35                      37
Teachers_Needed_To_Meet_UBE35         37
Enrolment_Change_PCT_vs_Prev_Year    180
Source                                 0
dtype: int64

### **HANDLING MISSING VALUES**

#### **The dataset combines two sources:**

**Lagos Bureau of Statistics (2016–2020):** recorded enrolment and teacher ratios, but not classrooms or toilets.

**DNEMIS (2024/25):** recorded classrooms and toilets, but not enrolment by gender.

Most missing values exist because a source never collected that information. They are not errors.

#### **Why I Did Not Fill The Missing Values:**
**Not with Zero(0):** 0 is a real number. A toilet ratio of 0 would wrongly suggest perfect conditions and distort the rankings and the model.

**Not with the Median:** in the 2016–2020 rows, classroom and toilet columns are completely empty, so a median would be invented data, not a real estimate.

**Not with "Not Provided":** text in a numeric column turns it into text, which stops calculations, sorting, charts and modelling.

#### **Why I left them as NaN:** Python recognises NaN as "no value". It skips NaN in calculations and still allows sorting, charting and modelling.

#### **Why I split the data:** each part is used for the task it supports.
**Machine learning uses the 2016–2020 rows,** which have four years of teacher-ratio history.

**Resource-gap ranking uses the 2024/25 rows,** which include classroom and toilet ratios.

##### Each subset keeps only the columns available for it, which removes most missing values without creating false data.

In [14]:
# To Check & Know the Columns in the Dataset

df_clean.columns

Index(['Row_ID', 'State', 'Ownership', 'Level', 'LGA', 'Granularity',
       'Data_Year', 'Year_Start', 'Learners', 'Male_Learners',
       'Female_Learners', 'Female_Learners_PCT', 'Learner_Teacher_Ratio',
       'Learner_Classroom_Ratio', 'Learner_Toilet_Ratio',
       'Female_Teachers_PCT', 'Special_Needs_Learners', 'Est_Teachers',
       'Est_Classrooms', 'Est_Toilets', 'LTR_Gap_vs_UBE35',
       'Teachers_Needed_To_Meet_UBE35', 'Enrolment_Change_PCT_vs_Prev_Year',
       'Source'],
      dtype='str')

#### SPLITTING THE DATA

In [15]:
# 1. ML dataset: 2016-2020 public rows, only columns that exist there

ml_cols = [
    "LGA", "Level", "Year_Start", "Learners", "Male_Learners",
    "Female_Learners", "Female_Learners_PCT", 
    "Learner_Teacher_Ratio", "Est_Teachers",
    "LTR_Gap_vs_UBE35", "Teachers_Needed_To_Meet_UBE35", 
    "Enrolment_Change_PCT_vs_Prev_Year"
]

ml_df = df_clean[df_clean["Year_Start"] <= 2019][ml_cols]
print(ml_df.isnull().sum())

# 2. Ranking dataset: 2024/25 rows, with classroom and toilet ratios

rank_cols =[
    "LGA", "Ownership", "Level", "Learners",
    "Learner_Teacher_Ratio", "Learner_Classroom_Ratio",
    "Learner_Toilet_Ratio", "Female_Teachers_PCT",
    "Special_Needs_Learners", "LTR_Gap_vs_UBE35"
]

rank_df = df_clean[df_clean["Year_Start"] == 2024][rank_cols]
print(rank_df.isnull().sum())

LGA                                   0
Level                                 0
Year_Start                            0
Learners                              0
Male_Learners                         0
Female_Learners                       0
Female_Learners_PCT                   0
Learner_Teacher_Ratio                 0
Est_Teachers                          0
LTR_Gap_vs_UBE35                      0
Teachers_Needed_To_Meet_UBE35         0
Enrolment_Change_PCT_vs_Prev_Year    60
dtype: int64
LGA                         0
Ownership                   0
Level                       0
Learners                    0
Learner_Teacher_Ratio      37
Learner_Classroom_Ratio    58
Learner_Toilet_Ratio       20
Female_Teachers_PCT        37
Special_Needs_Learners      0
LTR_Gap_vs_UBE35           37
dtype: int64

#### **CREATING THE FINAL ML TABLES**

##### After splitting, each table still contained a small number of rows with missing values. This step keeps only complete rows for each task, without filling in any values.

##### **ML TABLE:** The 2016/17 rows were removed from the ML table because enrolment change cannot be calculated for the first year; there is no previous year to compare with. Filling these values would have introduced false data. The final ML table has 180 complete rows (2017/18–2019/20).

In [16]:
# Make the Final ML

# ML: Leave out 2016/17 (No Previous Year To Compare)
ml_final = ml_df.dropna()
print(ml_final.shape)
print(ml_final.isnull().sum())

(180, 12)
LGA                                  0
Level                                0
Year_Start                           0
Learners                             0
Male_Learners                        0
Female_Learners                      0
Female_Learners_PCT                  0
Learner_Teacher_Ratio                0
Est_Teachers                         0
LTR_Gap_vs_UBE35                     0
Teachers_Needed_To_Meet_UBE35        0
Enrolment_Change_PCT_vs_Prev_Year    0
dtype: int64

In [17]:
missing_rows = rank_df[rank_df.isnull().any(axis=1)]
print(missing_rows.groupby(["Ownership", "Level"]).size())

Ownership  Level
Private    All levels    20
Public     IQS           20
           Tech/Voc      18
dtype: int64

#### **Identifying the Source of Missing Values in the Ranking Table**

##### Before deciding how to handle the missing values in the 2024/25 ranking data, I checked which rows they came from. This showed whether the gaps were spread randomly across the data or concentrated in particular school types.

##### The check found that all missing values came from three groups: private schools (20 rows), Islamiyya/Quranic schools (IQS, 20 rows) and technical/vocational schools (18 rows). Public Primary, JSS and SSS rows had no missing values.

#### **CREATING THE FINAL RANKING TABLES**

##### After splitting, each table still contained a small number of rows with missing values. This step keeps only complete rows for each task, without filling in any values.

##### **Ranking Table:** All missing values in the 2024/25 data came from private schools, Islamiyya/Quranic schools (IQS) and technical/vocational schools. Public Primary, JSS and SSS rows were complete. The ranking therefore uses only these 60 rows. These are also the schools that government and NGOs support directly with teachers and facilities, which is the focus of this tool.

In [18]:
# Ranking: Public Primary, JSS, SSS Only (Complete Data)

rank_final = rank_df[
    (rank_df["Ownership"] == "Public") &
    (rank_df["Level"] .isin(["Primary", "JSS", "SSS"]))
]

print(rank_final.shape)
print()
print(rank_final.isnull().sum())
print()
print(rank_final.isnull().sum().sum())

(60, 10)

LGA                        0
Ownership                  0
Level                      0
Learners                   0
Learner_Teacher_Ratio      0
Learner_Classroom_Ratio    0
Learner_Toilet_Ratio       0
Female_Teachers_PCT        0
Special_Needs_Learners     0
LTR_Gap_vs_UBE35           0
dtype: int64

0

##### CHECKING FOR DUPLICATE ROWS

In [19]:
# To Check Duplicate Values in the Dataset

print(f"Duplicate Rows: {df_clean.duplicated().sum()}")
print()
print("THE DUPLICATE ROWS:")
df[df.duplicated(keep=False)].sort_values("Year_Start")

Duplicate Rows: 0

THE DUPLICATE ROWS:

Empty DataFrame
Columns: [Row_ID, State, Ownership, Level, LGA, Granularity, Data_Year, Year_Start, Learners, Male_Learners, Female_Learners, Female_Learners_PCT, Learner_Teacher_Ratio, Learner_Classroom_Ratio, Learner_Toilet_Ratio, Female_Teachers_PCT, Special_Needs_Learners, Est_Teachers, Est_Classrooms, Est_Toilets, LTR_Gap_vs_UBE35, Teachers_Needed_To_Meet_UBE35, Enrolment_Change_PCT_vs_Prev_Year, Source]
Index: []

[0 rows x 24 columns]

In [20]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Row_ID                             360 non-null    str
 1   State                              360 non-null    str
 2   Ownership                          360 non-null    str
 3   Level                              360 non-null    str
 4   LGA                                360 non-null    str
 5   Granularity                        360 non-null    str
 6   Data_Year                          360 non-null    str
 7   Year_Start                         360 non-null    int64
 8   Learners                           360 non-null    int64
 9   Male_Learners                      240 non-null    float64
 10  Female_Learners                    240 non-null    float64
 11  Female_Learners_PCT                340 non-null    float64
 12  Learner_Teacher_Ratio              323 non-null    float64
 13  Learner_Classroom_Ratio            62 non-null     float64
 14  Learner_Toilet_Ratio               100 non-null    float64
 15  Female_Teachers_PCT                83 non-null     float64
 16  Special_Needs_Learners             120 non-null    Int64
 17  Est_Teachers                       323 non-null    float64
 18  Est_Classrooms                     62 non-null     float64
 19  Est_Toilets                        100 non-null    float64
 20  LTR_Gap_vs_UBE35                   323 non-null    float64
 21  Teachers_Needed_To_Meet_UBE35      323 non-null    Int64
 22  Enrolment_Change_PCT_vs_Prev_Year  180 non-null    float64
 23  Source                             360 non-null    str
dtypes: Int64(2), float64(12), int64(2), str(8)
memory usage: 68.3 KB

In [21]:
df_clean.describe()

,Year_Start,Learners,Male_Learners,Female_Learners,Female_Learners_PCT,Learner_Teacher_Ratio,Learner_Classroom_Ratio,Learner_Toilet_Ratio,Female_Teachers_PCT,Special_Needs_Learners,Est_Teachers,Est_Classrooms,Est_Toilets,LTR_Gap_vs_UBE35,Teachers_Needed_To_Meet_UBE35,Enrolment_Change_PCT_vs_Prev_Year
count,360.000000,360.000000,240.000000,240.000000,340.000000,323.000000,62.000000,100.000000,83.000000,120.0,323.000000,62.000000,100.000000,323.000000,323.0,180.000000
mean,2019.666667,16749.588889,8158.858333,8482.016667,51.396471,36.214551,53.933871,34.527000,68.357831,42.466667,745.086687,339.135484,848.354000,1.214551,63.866873,1.962778
std,3.201671,18746.251337,5158.472373,5101.810144,5.997171,16.294312,25.671768,22.171771,10.180027,115.927675,1569.820422,265.042293,1624.843349,16.294312,118.857727,7.052651
min,2016.000000,0.000000,1849.000000,1911.000000,16.200000,7.600000,7.900000,0.500000,41.600000,0.0,86.700000,23.000000,5.000000,-27.400000,0.0,-14.600000
25%,2017.000000,8516.250000,4644.000000,5010.500000,49.700000,26.000000,33.300000,15.950000,63.950000,0.0,292.800000,158.300000,153.050000,-9.000000,0.0,-2.950000
50%,2018.500000,13158.000000,6921.500000,7217.500000,50.900000,33.000000,54.750000,33.650000,69.100000,7.0,419.800000,226.650000,293.000000,-2.000000,0.0,1.650000
75%,2024.000000,19754.250000,9409.000000,10267.000000,52.600000,44.000000,72.975000,47.725000,74.300000,32.0,590.800000,445.275000,564.725000,9.000000,85.0,5.525000
max,2024.000000,228650.000000,29010.000000,29392.000000,82.600000,117.700000,100.100000,86.100000,88.400000,1016.0,17322.000000,1411.900000,10393.200000,82.700000,848.0,31.600000

In [22]:
ml_final.isnull().sum()
print()
rank_final.isnull().sum()

LGA                        0
Ownership                  0
Level                      0
Learners                   0
Learner_Teacher_Ratio      0
Learner_Classroom_Ratio    0
Learner_Toilet_Ratio       0
Female_Teachers_PCT        0
Special_Needs_Learners     0
LTR_Gap_vs_UBE35           0
dtype: int64

##### SAVE THE CLEAN FILES

In [23]:
import os
os.makedirs("data", exist_ok=True)

df_clean.to_csv("data/Lagos_Clean_Full.csv", index=False)
ml_final.to_csv("data/Lagos_ML_Data.csv", index=False)
rank_final.to_csv("data/Lagos_Ranking_Data.csv", index=False)

#### **Saving the Cleaned Datasets**

##### The cleaned data was saved as three separate files for two reasons. First, the data comes from two sources that recorded different information: the 2016–2020 report had four years of student and teacher data but no classrooms or toilets, while the 2024/25 report had classrooms and toilets for one year only. Second, each part of the project needs different data. Keeping them separate means every task uses only complete, real data, with no invented values.

**Lagos_Clean_Full.csv (360 rows):** the complete cleaned dataset with missing values kept as NaN, used for exploratory data analysis and the RAG assistant.

**Lagos_ML_Data.csv (180 rows):** complete rows from 2017/18 to 2019/20, used to train and test the machine learning models.

**Lagos_Ranking_Data.csv (60 rows):** complete 2024/25 rows for public Primary, JSS and SSS schools, used to rank LGAs by resource gaps.